// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgnXSy3P20nxiYaztoUtlHpYrlHppwmDQ',
    appId: '1:776982835990:web:ae4bd0d624a7bdba971637',
    messagingSenderId: '776982835990',
    projectId: 'task-manager-1a961',
    authDomain: 'task-manager-1a961.firebaseapp.com',
    storageBucket: 'task-manager-1a961.appspot.com',
    measurementId: 'G-KYJFWSS09F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlgJ92KfFilx2N46v6qg2-MqmiJqsWAM',
    appId: '1:776982835990:android:67246c1fd6162bab971637',
    messagingSenderId: '776982835990',
    projectId: 'task-manager-1a961',
    storageBucket: 'task-manager-1a961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGkOoV2Otig39IU1JroEJMrieAPMwCGyg',
    appId: '1:776982835990:ios:8cc0cb4aa7169ec1971637',
    messagingSenderId: '776982835990',
    projectId: 'task-manager-1a961',
    storageBucket: 'task-manager-1a961.appspot.com',
    androidClientId: '776982835990-cd8l8gdcr5vjcbuhh2rn7a75ae1h80qi.apps.googleusercontent.com',
    iosClientId: '776982835990-cbtk4i74vtfiuj6i0lcpsi4a5oit5dk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGkOoV2Otig39IU1JroEJMrieAPMwCGyg',
    appId: '1:776982835990:ios:8cc0cb4aa7169ec1971637',
    messagingSenderId: '776982835990',
    projectId: 'task-manager-1a961',
    storageBucket: 'task-manager-1a961.appspot.com',
    androidClientId: '776982835990-cd8l8gdcr5vjcbuhh2rn7a75ae1h80qi.apps.googleusercontent.com',
    iosClientId: '776982835990-cbtk4i74vtfiuj6i0lcpsi4a5oit5dk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgnXSy3P20nxiYaztoUtlHpYrlHppwmDQ',
    appId: '1:776982835990:web:2b38c784bc069b23971637',
    messagingSenderId: '776982835990',
    projectId: 'task-manager-1a961',
    authDomain: 'task-manager-1a961.firebaseapp.com',
    storageBucket: 'task-manager-1a961.appspot.com',
    measurementId: 'G-6YY99YN1QT',
  );

}